version: '2'
services:
  db:
    image: mysql:5.5
    container_name: db
    restart: always
    env_file:
      - ./config/mysql.env
    ports:
      - "8886:3306"
    volumes:
      - ./.data/db:/var/lib/mysql
  api:
    depends_on:
      - db
    image: getdirectus/directus:6.4
    container_name: api
    ports:
     - "8888:8080"
    restart: always
    volumes:
      - ./.data/api-storage:/var/www/html/storage
      - ./config/directus_configuration.php:/var/www/api/configuration.php # not really working
    env_file:
      - ./config/api.env
    environment:
     - MYSQL_PORT_3306_TCP_ADDR=db
     - MYSQL_PORT_3306_TCP_PORT=3306
